spring.application.name=webshop
spring.datasource.url=jdbc:sqlserver://LAPTOP-T35UA31I\\MSSQLSERVER01:1433;databaseName=calisthenicsShop;TrustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.jpa.show-sql=true
